{{- if .Values.job.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cronjob.fullname" . }}-files
  labels:
    {{- include "cronjob.labels" . | nindent 4 }}
data:
{{- range .Values.job.files }}
  {{ .name }}: |- {{ .content | nindent 4 }}
{{- end }}
{{- end }}