apiVersion: v2
appVersion: v1.1.3
description: Configuration management and auto-import tool for Radarr/Sonarr custom formats and profiles.
name: profilarr
version: 1.1.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
