apiVersion: v2
name: tandoor-recipes
description: The recipe manager that allows you to manage your ever growing collection of digital recipes.
type: application
version: 1.0.3
appVersion: 1.5.35
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default