image:
  repository: vabene1111/recipes
  tag: "1.5.34"

ports:
  - name: http
    containerPort: 8080
    servicePort: 80
    protocol: TCP

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 2
  failureThreshold: 10
  httpGet:
    path: /api/
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /api/
    port: http