image:
  repository: vabene1111/recipes
  tag: "2.2.0"

ports:
  - name: http
    containerPort: 8080
    servicePort: 80
    protocol: TCP

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 1
  failureThreshold: 20
  httpGet:
    path: /
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /
    port: http