image:
  repository: vabene1111/recipes
  tag: "1.5.26"
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

ingress:
  enabled: false

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 1
  failureThreshold: 20
  httpGet:
    path: /
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /
    port: http