apiVersion: v2
appVersion: "4.0.11"
home: https://github.com/Sonarr/Sonarr
name: sonarr
description: Sonarr is a PVR for usenet and bittorrent users.
type: application
version: 1.0.5
dependencies:
  - name: helmet
    version: 0.11.0
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
