apiVersion: v2
appVersion: "v23.05.1"
description: A dead simple static HOMe for your servER to keep your services on hand from a simple yaml config
name: homer
version: 3.0.0
dependencies:
  - name: helmet
    version: 0.14.0
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
