apiVersion: v2
appVersion: 1.34.0
description: Overseerr is a request management and media discovery tool built to work with your existing Plex ecosystem.
name: overseerr
version: 2.1.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
