image:
  repository: linuxserver/overseerr
  tag: 1.34.0
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 5055
    protocol: TCP

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ingress:
  enabled: false

