image:
  repository: linuxserver/overseerr
  tag: 1.34.0

ports:
  - name: http
    containerPort: 5055
    servicePort: 80
    protocol: TCP

livenessProbe:
  enabled: true
  httpGet:
    path: /api/v1/status
    port: http

readinessProbe:
  enabled: true
  httpGet:
    path: /api/v1/status
    port: http