apiVersion: v2
appVersion: "231128"
description: PhotoPrism is an AI-Powered Photos App for the Decentralized Web.
name: photoprism
version: 1.1.0
dependencies:
  - name: helmet
    version: 0.11.0
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
