image:
  repository: photoprism/photoprism
  tag: "20220121"
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 2342
    protocol: TCP

ingress:
  enabled: false

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 1
  failureThreshold: 20
  httpGet:
    path: /api/v1/status
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /api/v1/status
    port: http

envVarsConfigMap: "{{ printf \"%s-%s\" (include \"common.names.fullname\" $) \"config\" }}"

photoPrismConfig:
  PHOTOPRISM_ADMIN_PASSWORD: "admin"
  PHOTOPRISM_HTTP_HOST: "0.0.0.0"
  PHOTOPRISM_HTTP_PORT: "2342"
  PHOTOPRISM_DISABLE_RESTART: "true"
  PHOTOPRISM_FFMPEG_ENCODER: "vaapi"
  PHOTOPRISM_SITE_TITLE: "Home-net private photos"
  PHOTOPRISM_SITE_CAPTION: "A self hosted collection of private photos"
  PHOTOPRISM_LOG_LEVEL: "info"