apiVersion: v2
appVersion: 4.5.3
description: The free and easy binary newsreader
name: sabnzbd
version: 2.1.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
