apiVersion: v2
appVersion: 4.5.0
description: The free and easy binary newsreader
name: sabnzbd
version: 1.2.0
dependencies:
  - name: helmet
    version: 0.6.5
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
