apiVersion: v2
appVersion: "4.3.3"
description: The free and easy binary newsreader
name: sabnzbd
version: 1.0.0
dependencies:
  - name: helmet
    version: 0.6.5
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults
