apiVersion: v2
appVersion: "10.8.10"
description: The Free Software Media System
name: jellyfin
version: 1.1.0
dependencies:
  - name: helmet
    version: 0.6.5
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults