apiVersion: v2
appVersion: 10.10.6
description: The Free Software Media System
name: jellyfin
version: 2.0.1
dependencies:
  - name: common
    version: 1.0.1
    repository: https://common-chart.home-net.app
    import-values:
      - default