image:
  repository: linuxserver/jellyfin
  tag: 10.8.13
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "4000m"

ports:
  - name: http
    containerPort: 8096
    protocol: TCP

#envVars:
#  - name: JELLYFIN_PublishedServerUrl
#    value: 192.168.0.5

ingress:
  enabled: false