image:
  repository: linuxserver/jellyfin
  tag: 10.10.6

ports:
  - name: http
    containerPort: 8096
    servicePort: 80
    protocol: TCP

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 18
  httpGet:
    path: /
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /health
    port: http

persistentVolumeClaims: [ ]