image:
  repository: linuxserver/jellyfin
  tag: 10.8.13
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "4000m"

ports:
  - name: http
    containerPort: 8096
    protocol: TCP

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  httpGet:
    path: /health
    port: http

#envVars:
#  - name: JELLYFIN_PublishedServerUrl
#    value: 192.168.0.5

ingress:
  enabled: false