image:
  repository: linuxserver/jellyfin
  tag: 10.8.10
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "500m"
  limits:
    memory: "4Gi"
    cpu: "5000m"

#envVars:
#  - name: JELLYFIN_PublishedServerUrl
#    value: 192.168.0.5

ingress:
  enabled: false

serviceMonitor:
  enabled: true

# EnableMetrics is a setting available in the XML (unfortunately not available through environment variables) that
# enables prometheus compatible metrics.
initContainers:
  - name: enable-metrics
    image: busybox:1.28
    command: [ '/bin/sh', '-c' ]
    args:
      - |
        sed -i 's/<EnableMetrics>false<\/EnableMetrics>/<EnableMetrics>true<\/EnableMetrics>/' config/system.xml

persistence:
  config:
    name: &volume-name-config jellyfin-config
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  data:
    name: &volume-name-data jellyfin-data
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 64Gi

extraVolumeMounts:
  - mountPath: /config
    name: *volume-name-config
  - mountPath: /data
    name: *volume-name-data
