image:
  repository: linuxserver/jellyfin
  tag: 2021.12.16
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 8096
    protocol: TCP

# Need to completely shut down all instances due to database lock
updateStrategy:
  type: Recreate

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 18
  httpGet:
    path: /
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  httpGet:
    path: /health
    port: http

#envVars:
#  - name: JELLYFIN_PublishedServerUrl
#    value: 192.168.0.5

ingress:
  enabled: false

pvcs: []
#  - name: config
#    annotations: {}
#    accessModes:
#      - ReadWriteOnce
#    request:
#      storage: 128Mi