apiVersion: v2
appVersion: 1.5.2
description: Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
name: bazarr
version: 2.0.1
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
