apiVersion: v2
appVersion: "1.4.5"
description: Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
name: bazarr
version: 2.0.0
dependencies:
  - name: common
    version: 0.2.1
    repository: https://common-chart.home-net.app
    import-values:
      - default
