apiVersion: v2
appVersion: 2.6.3
description: Heimdall is a way to organise all those links to your most used web sites and web applications in a simple way.
name: bazarr
version: 1.0.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
