image:
  repository: eclipse-mosquitto
  tag: 1.6.12
  pullPolicy: IfNotPresent

ports:
  - name: mqtt
    containerPort: 1883
    protocol: "TCP"

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"

ingress:
  enabled: false

sidecars:
  - name: exporter
    image: "sapcc/mosquitto-exporter:0.8.0"
    imagePullPolicy: IfNotPresent
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 32Mi
    ports:
      - containerPort: 9234
        name: prometheus
        protocol: TCP

serviceMonitor:
  enabled: true
  port: prometheus

