image:
  repository: haugene/transmission-openvpn
  tag: 5.3.1
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 9091
    protocol: TCP

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http

containerSecurityContext:
#  enabled: true
  capabilities:
    add:
      - NET_ADMIN