image:
  repository: linuxserver/transmission
  tag: 4.0.6

ports:
  - name: http
    containerPort: 9091
    servicePort: 80
    protocol: TCP

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http