image:
  repository: linuxserver/transmission
  tag: 4.0.6
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 9091
    protocol: TCP

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http