apiVersion: v2
appVersion: 2.16.0
description: Tautulli is a 3rd party application that you can run alongside your Plex Media Server to monitor activity and track various statistics.
name: tautulli
version: 2.2.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
