apiVersion: v2
appVersion: 2.15.2
description: Tautulli is a 3rd party application that you can run alongside your Plex Media Server to monitor activity and track various statistics.
name: tautulli
version: 2.0.0
dependencies:
  - name: common
    version: 0.2.1
    repository: https://common-chart.home-net.app
    import-values:
      - default
