image:
  repository: linuxserver/tautulli
  tag: 2.15.2
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 8181
    protocol: TCP

livenessProbe:
  enabled: true
  httpGet:
    path: /status
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /status
    port: http