image:
  repository: flaresolverr/flaresolverr
  tag: v3.3.21
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 8191
    servicePort: 80
    protocol: TCP

envVarsBase:
  - name: LOG_LEVEL
    value: info

readinessProbe:
  enabled: true
  initialDelaySeconds: 3
  periodSeconds: 1
  failureThreshold: 12
  httpGet:
    path: /
    port: http