image:
  repository: linuxserver/deluge
  tag: 2.1.1
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

ingress:
  enabled: false

livenessProbe:
  enabled: true
  periodSeconds: 3
  httpGet:
    path: /
    port: http

readinessProbe:
  enabled: true
  initialDelaySeconds: 3
  periodSeconds: 1
  failureThreshold: 12
  httpGet:
    path: /
    port: http
