image:
  repository: paperlessngx/paperless-ngx
  tag: "2.15"
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 8000
    servicePort: 80
    protocol: TCP

ingress:
  enabled: false

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 1
  failureThreshold: 20
  httpGet:
    path: /
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /
    port: http

envVarsBase:
  - name: "PAPERLESS_PORT"
    value: "8000"