image:
  repository: linuxserver/wikijs
  tag: 2.5.305
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 3000
    protocol: TCP

resources:
  requests:
    memory: "128Mi"
    cpu: "150m"
  limits:
    memory: "256Mi"
    cpu: "300m"

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: http

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: http

startupProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 3
  failureThreshold: 10
  httpGet:
    path: /
    port: http

ingress:
  enabled: true
  hostname: wiki.example.com
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "clusterissuer"

envVars:
  - name: DB_TYPE
    value: postgres
  - name: DB_NAME
    value: wikijs
