apiVersion: v2
name: stackgres-cluster
description: Utility to create a stackgres cluster using CRs
type: application
version: 0.3.0
dependencies:
  - name: common
    version: "2.6.0"
    repository: "https://charts.bitnami.com/bitnami"
