apiVersion: v2
appVersion: 2.18.2
description: Maintainerr is a one-stop-shop for handling outlying shows and movies that take up precious space on your server.
name: maintainerr
version: 1.0.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
