apiVersion: v2
appVersion: "0.23.0"
description: The Todo-app to organize your life.
name: vikunja
version: 1.3.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
