image:
  repository: vikunja/vikunja
  tag: 0.24.6

ports:
  - name: http
    containerPort: 3456
    servicePort: 80
    protocol: TCP

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /health
    port: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  failureThreshold: 3
  httpGet:
    path: /health
    port: http