apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
data:
  {{ if .Values.jellyfin.publishedServerUrl -}}
  JELLYFIN_PublishedServerUrl: {{ .Values.jellyfin.publishedServerUrl }}
  {{ end }}