apiVersion: v2
appVersion: "2024.5.13-a0bc346"
description: Collection of handy online tools for developers, with great UX as a web app.
name: it-tools
version: 2.0.0
dependencies:
  - name: common
    version: 0.2.1
    repository: https://common-chart.home-net.app
    import-values:
      - default