apiVersion: v2
appVersion: 2.9.8
description: Cleanuparr is a tool for automating the cleanup of unwanted or blocked files in Sonarr, Radarr, and supported download clients like qBittorrent.
name: cleanuparr
version: 1.3.1
dependencies:
  - name: common
    version: 1.2.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
