apiVersion: v2
appVersion: 2.0.14
description: Cleanuparr is a tool for automating the cleanup of unwanted or blocked files in Sonarr, Radarr, and supported download clients like qBittorrent.
name: cleanuparr
version: 1.0.1
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
