image:
  repository: ghcr.io/cleanuparr/cleanuparr
  tag: 2.3.3

ports:
  - name: http
    containerPort: 11011
    servicePort: 80
    protocol: TCP

envVarsBase:
  - name: PORT
    value: 11011

livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
  httpGet:
    path: /
    port: http

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /
    port: http
