apiVersion: v2
name: externalsecret
description: Utility to create external secrets using "external-secrets" CRD
type: application
version: 0.1.1
dependencies:
  - name: common
    version: "2.6.0"
    repository: "https://charts.bitnami.com/bitnami"
