apiVersion: v2
appVersion: "2.0.4"
description: MicroBin is a super tiny, feature rich, configurable, self-contained and self-hosted paste bin web application.
name: microbin
version: 1.0.2
dependencies:
  - name: helmet
    version: 0.14.0
    repository: https://companyinfo.github.io/helm-charts
    import-values:
      - defaults