apiVersion: v2
appVersion: "2.0.4"
description: MicroBin is a super tiny, feature rich, configurable, self-contained and self-hosted paste bin web application.
name: microbin
version: 2.0.0
dependencies:
  - name: common
    version: 1.0.1
    repository: https://common-chart.home-net.app
    import-values:
      - default