image:
  repository: danielszabo99/microbin
  tag: 2.0.4

ports:
  - name: http
    containerPort: 8080
    servicePort: 80
    protocol: TCP

livenessProbe:
  enabled: true
  periodSeconds: 3
  httpGet:
    path: /
    port: http

readinessProbe:
  enabled: true
  initialDelaySeconds: 3
  periodSeconds: 1
  failureThreshold: 12
  httpGet:
    path: /
    port: http

envVarsBase:
  - name: 'MICROBIN_TITLE'
    value: 'Homenet paste bin'
  - name: 'MICROBIN_DISABLE_TELEMETRY'
    value: 'true'
  - name: 'MICROBIN_DISABLE_UPDATE_CHECKING'
    value: 'true'
  - name: 'MICROBIN_HIGHLIGHTSYNTAX'
    value: 'true'
  - name: 'MICROBIN_PRIVATE'
    value: 'true'
  - name: 'MICROBIN_HIDE_FOOTER'
    value: 'true'
  - name: 'MICROBIN_QR'
    value: 'true'
  - name: 'MICROBIN_THREADS'
    value: '1'
  - name: 'MICROBIN_PORT'
    value: '8080'