apiVersion: v2
appVersion: 5.22.4
home: https://github.com/Radarr/Radarr
description: A fork of Sonarr to work with movies à la Couchpotato
name: radarr
version: 2.0.0
dependencies:
  - name: common
    version: 1.0.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
