image:
  repository: linuxserver/radarr
  tag: 5.22.4

ports:
  - name: http
    containerPort: 7878
    servicePort: 80
    protocol: TCP

livenessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /ping
    port: http