{{- if or (not .Values.secrets) (eq (len .Values.secrets) 0) }}
  {{ fail "Error: secrets must not be empty" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.fullname" . }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.secrets }}
  "{{ $k }}": {{ printf "%v" $v | b64enc }}
{{- end }}