apiVersion: v2
appVersion: 3.4.3
description: Collection of handy online tools for developers, with great UX as a web app.
name: joplin
version: 1.0.1
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default