{{- if (.Values.cluster.backup).enabled }}
apiVersion: stackgres.io/v1beta1
kind: SGObjectStorage
metadata:
  name: {{ include "common.names.name" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
    {{- if .Values.annotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.annotations "context" $) | nindent 4 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
spec: {{ .Values.cluster.backup.storage | required "Specify storage for backup" | toYaml | nindent 2 }}
{{- end }}