apiVersion: v2
name: secretstore
description: Utility to create external secret stores using "external-secrets" CRD
type: application
version: 0.1.0
dependencies:
  - name: common
    version: "2.6.0"
    repository: "https://charts.bitnami.com/bitnami"
