image:
  repository: linuxserver/prowlarr
  tag: 1.11.4
  pullPolicy: IfNotPresent

ports:
  - name: http
    containerPort: 9696
    protocol: TCP

livenessProbe:
  enabled: true
  exec:
    command:
      - /usr/bin/env
      - bash
      - -c
      - curl --fail localhost:9696/api/v1/system/status?apiKey=`IFS=\> && while
        read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /ping
    port: http