image:
  repository: linuxserver/prowlarr
  tag: 1.37.0

ports:
  - name: http
    containerPort: 9696
    servicePort: 80
    protocol: TCP

livenessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /ping
    port: http