#objectStorages:
#  - name: default
#    spec:
#      type: gcs
#      gcs:
#        bucket: home-net-postgres-backup
#        gcpCredentials:
#          secretKeySelectors:
#            serviceAccountJSON:
#              key: serviceAccountJSON
#              name: wikijs-gcp-serviceaccount
#configurations:
#  pooling:
#    - name: small
#      data:
#        pgbouncer:
#          max_client_conn: '100'
#  postgres:
#    - name: tiny
#      postgresVersion: 15
#      data:
#        autovacuum_work_mem: 64MB
#        maintenance_work_mem: 128MB
#    - name: small
#      postgresVersion: 15
#      data:
#        autovacuum_work_mem: 128MB
#        maintenance_work_mem: 256MB
#instanceProfiles:
#  - name: tiny
#    resources:
#      cpu: 300m
#      memory: 250Mi
#  - name: small
#    resources:
#      cpu: 500m
#      memory: 500Mi