cluster:
  postgres:
    version: latest
#  resources:
#    cpu: "1"
#    memory: 1Gi
#  persistence:
#    size: 5Gi
#    storageClass: default
#  backup:
#    enabled: true
#    retention: 5
#    cronSchedule: 0 3 * * *
#    compression: lz4
#    path: /backup/wikijs
#    storage:
#      type: gcs
#      gcs:
#        bucket: home-net-postgres-backup
#        gcpCredentials:
#          secretKeySelectors:
#            serviceAccountJSON:
#              key: serviceAccountJSON
#              name: wikijs-gcp-serviceaccount
