apiVersion: v2
appVersion: 8.2.10
description: Huntarr is an automatic missing content hunter for Sonarr, Radarr, Lidarr, Readarr, and Whisparr.
name: huntarr
version: 1.1.0
dependencies:
  - name: common
    version: 1.1.0
    repository: https://common-chart.home-net.app
    import-values:
      - default
