image:
  repository: huntarr/huntarr
  tag: 8.1.11

ports:
  - name: http
    containerPort: 9705
    servicePort: 80
    protocol: TCP

envVarsBase:
  - name: HUNTARR_PORT
    value: "9705"

livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
  httpGet:
    path: /
    port: http

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 15
  httpGet:
    path: /
    port: http